name: Supabase Ingest Cron

on:
  schedule:
    - cron: "*/5 * * * *" # cada 5 minutos (UTC)
  workflow_dispatch: {}

jobs:
  call-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          curl -sS -X POST \ -H "x-cron-secret: ZwVE8_kaMrw3Jxq" -H "Authorization: Bearer dd14b4d53cbaa0b19edf98d61c1150942940a9f0b8400d0714cb581adfd7f3a1" \ https://qglltyflknoqcimpburc.supabase.co/functions/v1/dynamic-handler
