name: Supabase Ingest Cron

on:
  schedule:
    - cron: "*/5 * * * *" # cada 5 minutos (UTC)
  workflow_dispatch: {}

jobs:
  call-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
        run: curl -sS -X POST \ -H "x-cron-secret: ${CRON_SECRET}" -H "Authorization: Bearer ${ACCESS_TOKEN}" \ https://${PROJECT_REF}.functions.supabase.co/functions/v1/dynamic-handler
